### ISSUE TITLE
A question about the Authorization (Fitbit). Thanks.

### ISSUE THREAD

**Issue by IJDesign** [04nd01/fitjunction#8]
Hi, thanks for developing this tool to pull the data from Fitbit. I followed your instructions to install and put the repository in the root of my web server. However, when I open the "http://localhost/?mode=auth," in a browser, it shows the file list in the directory. How could I initiate the authentication procedure? Could you give me a hint? Thank you very much. 

Best Regards,

Yaliang

**Comment by 04nd01** [comment]
The app shouldn't be able to do something like showing a file list, but if another program was acting as a Webserver there should be an error message right away. Do you see any errors when you run the main.js from command line?

In windows, if another application is already listening on port 80 you can find out what it is through resource manager. To do that,  run resmon.exe, go to "Network > Listening Ports" and it should show the name of the application.
